version: '2'
services:
  postgres:
    image: sarlos/postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
    build:
      context: .
volumes:
  data:
    driver: local
